DROP TABLE game_history CASCADE CONSTRAINTS;
DROP TABLE table_personal CASCADE CONSTRAINTS;
DROP TABLE personal_contract_history CASCADE CONSTRAINTS;
DROP TABLE "table" CASCADE CONSTRAINTS;
DROP TABLE personal CASCADE CONSTRAINTS;
DROP TABLE customer CASCADE CONSTRAINTS;
DROP TABLE game CASCADE CONSTRAINTS;
-- DROP TABLE log_table CASCADE CONSTRAINTS;
