-- drop user casino;
CREATE USER casino IDENTIFIED BY oracle;

GRANT CREATE SESSION TO casino;
GRANT CREATE TABLE TO casino;
GRANT ALTER ANY TABLE TO casino;
GRANT DROP ANY TABLE TO casino;
GRANT INSERT ANY TABLE TO casino;
GRANT UPDATE ANY TABLE TO casino;
GRANT DELETE ANY TABLE TO casino;

GRANT CREATE PROCEDURE TO casino;
GRANT CREATE TRIGGER TO casino;

GRANT UNLIMITED TABLESPACE TO casino;
